### ISSUE TITLE
iOS safari 日期区间选择，起止日期相反。

### ISSUE THREAD

**Issue by apgmer** [deepkolos/vc-popup#12]
设备 ： ios 11 safari 以及 mac safari
safari 中日期区间显示，起止日期相反 
操作： 先点击某一个日期，再点击之前的日期，会出现如下情况
<img src="https://user-images.githubusercontent.com/9553342/41695545-00a1df6e-7542-11e8-89e1-5772cc40420f.jpg" width="300px">

**Comment by deepkolos** [comment]
收到, 不过因为手上无IOS设备, 可能处理bug需要点时间
