### ISSUE TITLE
为什么 picker 只返回 value, 而不返回这个 value 在 slots 中的下标呢。

### ISSUE THREAD

**Issue by LLoyou00** [deepkolos/vc-popup#4]
RT
另外，是否能够实现给 slots 传递一个 {key : ,value : } 这种形式的数据，给用户看到的都是 value，而当用户选择了之后返回的是 key

**Comment by deepkolos** [comment]
嗯, onComfirm只返回的是picker的$vm引用, 然后再通过picker的$vm去获取当前的状态, 也就是结果

至于` {key : ,value : }` 的values形式其实是支持的, 已经增加demo了

**导入label-key的形式**
https://deepkolos.github.io/vc-popup/#/popup-picker

使用可以参考这里
https://github.com/deepkolos/vc-popup/blob/master/example/pages/popup-picker.vue#L86

```
      labelKeySlots: [
          {
            values: [
              {
                text: '值0',
                value: 0, //可以附带其他值
                str: '0'
              },
              {
                text: '值1',
                value: 1,
                str: '1'
              },
              {
                text: '值2',
                value: 2,
                str: '2'
              }
            ],
            labelKey: 'text',  //通过该字段来指定需要选择的key
            defaultIndex: 2
          }
        ],
```

至于不返回key, 可以考虑使用indexOf

**Comment by LLoyou00** [comment]
Thank you very much.
