### ISSUE TITLE
调用 picker.open 后页面刷新

### ISSUE THREAD

**Issue by LLoyou00** [deepkolos/vc-popup#6]
之前在测试的时候发现弹出 picker 后页面会自动刷新，自动刷新后再手动刷新一次页面后就可以恢复正常，但是另一个同事的项目却没有这个问题。
排除其它的无关变量后发现我俩的项目区别在于：我的项目是传统的多页面项目，他的项目是 SPA。
在排除问题的过程中我发现，每次 picker 打开后，这个插件会在地址栏的 URL 之后加上 #?popup=Picker_0。
但是在加上这个字符串的瞬间，# 会被删除，然后页面就刷新了。
目前我的解决方法是在页面初始化后执行 `location.hash = '##'`
最后关于这个问题猜测如下：

- 插件在地址栏后添加 #?popup=Picker_0，但是 # 被删除，这就相当于是直接在 url 后面添加了 
?popup=Picker_0，正常情况下，这就会导致浏览器刷新。

- SPA 框架会 HACK localtion 对象，阻止了 localtion 的变动导致的页面刷新。

最后希望作者在下一个版本能解决一下这个问题。
Thank you！

**Comment by deepkolos** [comment]
@LLoyou00 先谢谢反馈~ 我会跟进的~

`#?popup=Picker_0`的作用是支持移动端的返回按钮, 比如在掘金的文章回复评论的时候, 想回看文章的内容再写评论, 习惯性按一下返回键然后网页关闭了, 体验不好, 所以增加了这项支持, 当然, 可能是我长期使用安卓导致的习惯.

因为需要bug重现, 是否可以提供一下测试的浏览器版本,  Vue的引入方式(script的方式? 没有使用vue-router?)

**Comment by deepkolos** [comment]
@LLoyou00 修复好了~ 可以更新测试一下~
