### ISSUE TITLE
Dialog 的 onConfirm 方法中无法重定向页面地址

### ISSUE THREAD

**Issue by LLoyou00** [deepkolos/vc-popup#9]
RT

![_20180428182057](https://user-images.githubusercontent.com/9455777/39395423-0b2a5fde-4b11-11e8-8797-e644844821d6.png)
如上图这样无法达到想要的效果，需要像注释的代码那样才能达到目的。

**Comment by deepkolos** [comment]
斯斯~ 这个bug比较隐晦, 需要仔细找找原因~

**Comment by deepkolos** [comment]
@LLoyou00 话说, 想问问是否有必要增加, 在结束动画之后才出发onConfirm/onCancel的需求捏?

**Comment by deepkolos** [comment]
已经找到原因了

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>location.href bug</title>
</head>
<body>
    <div id="box">点击跳转到自然志</div>
</body>
<script>
    var $box = document.getElementById('box');
    location.hash = 'test'
    $box.addEventListener('click', function(){
        location.href = "https://ziranzhi.com/"
        console.log('here');
        history.back()
        location.href = 'fail'
    })
</script>
</html>
```

https://github.com/deepkolos/vc-popup/blob/master/src/components/popup-dialog/index.vue#L100

之前是后面close, 之前是后面再执行close, close里边会导致一个href设置

**Comment by LLoyou00** [comment]
@deepkolos 问题好像并没有得到解决，我在两台安卓手机和一台 IOS8 上测试都无法跳转。
测试了 Chrome 没有这个问题，360Chrome 中问题依旧存在。
